### ISSUE TITLE
No variation in the output of igraph::walktrap.community wrt different random seeds

### ISSUE THREAD

**Issue by exilespacer** [chainsawriot/rstyle#25]
![image](https://user-images.githubusercontent.com/6258851/89728995-ddf07f00-da31-11ea-8dc9-1173f740eabc.png)

**Comment by lentychang** [comment]
### Try changing the seed in official rigraph test [script](https://github.com/igraph/rigraph/blob/675946d0d30a3e29b3562a76d25a52faf2332240/tests/testthat/test_walktrap.community.R#L9)
If the test still pass, then it means set.seed really has no influence on walktrap.community.

### Try without setting seed?
In c implementation, it says, if no seed is specified, the `time(0)`is used as seed, so, it should generate different result every time.

### Some information from c implementation:  
- From [Have set RNG explicitly](https://github.com/igraph/igraph/blob/eca5e809aab1aa5d4eca1e381389bcde9cf10490/src/random.c#L103):  

> Note that initializing a new random number generator is independent of the generator that the igraph functions themselves
> use. If you want to replace that, then please use igraph_rng_set_default().  

- More information regarding RNG in c implementation [rng_use_cases] (https://github.com/igraph/igraph/blob/eca5e809aab1aa5d4eca1e381389bcde9cf10490/src/random.c#L68)
